var express = require("express");
var app = express();
const path = require('path');
console.log(__dirname);
app.get("/", function (req, res) { res.sendFile(path.join(__dirname, '/home.html'))});
app.get("/home.html", function (req, res) { res.sendFile(path.join(__dirname, '/home.html'))});
app.get("/home.css", function (req, res) { res.sendFile(path.join(__dirname, '/home.css'))});
app.get("/angajati.html", function (req, res) { res.sendFile(path.join(__dirname, '/angajati.html'))});
app.get("/angajati.css", function (req, res) { res.sendFile(path.join(__dirname, '/angajati.css'))});
app.get("/contact.html", function (req, res) { res.sendFile(path.join(__dirname, '/contact.html'))});
app.get("/contact.css", function (req, res) { res.sendFile(path.join(__dirname, '/contact.css'))});
app.get("/pwork.html", function (req, res) { res.sendFile(path.join(__dirname, '/pwork.html'))});
app.get("/pwork.css", function (req, res) { res.sendFile(path.join(__dirname, '/pwork.css'))});
app.get("/script.js", function (req, res) { res.sendFile(path.join(__dirname, '/script.js'))});
app.get("/poze/ang1.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/ang1.jpg'))});
app.get("/poze/ang2.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/ang2.jpg'))});
app.get("/poze/ang3.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/ang3.jpg'))});
app.get("/poze/ang4.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/ang4.jpg'))});
app.get("/poze/background.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/background.jpg'))});
app.get("/poze/s1.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/s1.jpg'))});
app.get("/poze/s2.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/s2.jpg'))});
app.get("/poze/s3.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/s3.jpg'))});
app.get("/poze/s4.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/s4.jpg'))});
app.get("/poze/serv1.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/serv1.jpg'))});
app.get("/poze/serv2.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/serv2.jpg'))});
app.get("/poze/serv3.jpg", function (req, res) { res.sendFile(path.join(__dirname, '/poze/serv3.jpg'))});
app.get('*', function(req, res){
  res.status(404).sendFile(path.join(__dirname, '/404.html'));
});
app.listen(5000, function () { console.log("A pornit"); });
